# Generated by Django 4.2.1 on 2023-11-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='theme_label',
            field=models.CharField(choices=[('Coming of Age', 'Coming of Age'), ('Love and Relationships', 'Love and Relationships'), ('Good vs. Evil', 'Good vs. Evil'), ('Social Injustice', 'Social Injustice'), ('Self-Discovery', 'Self-Discovery'), ('Technology and Society', 'Technology and Society'), ('War and Peace', 'War and Peace'), ('Crime and Justice', 'Crime and Justice'), ('Cultural Diversity', 'Cultural Diversity'), ('Historical Reflection', 'Historical Reflection'), ('Political Intrigue', 'Political Intrigue'), ('Spirituality and Faith', 'Spirituality and Faith'), ('Ethics and Morality', 'Ethics and Morality'), ('Adventure and Exploration', 'Adventure and Exploration')], max_length=50),
        ),
    ]
