# Generated by Django 4.2.1 on 2023-11-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_movierating_theme_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='age_recommendation',
            field=models.CharField(choices=[('ALL', 'All Ages'), ('CHILD', 'Children'), ('TEEN', 'Teens'), ('ADULT', 'Adults')], default='ALL', max_length=100),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='theme_description',
            field=models.TextField(default='', max_length=2000, verbose_name='theme description'),
        ),
    ]
