# Generated by Django 4.2.1 on 2023-11-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='product_url',
            field=models.URLField(default=''),
        ),
    ]
