# Generated by Django 5.0.2 on 2024-05-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
