# Generated by Django 5.0.2 on 2024-02-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_suggestion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='product_url',
            field=models.URLField(default='', null=True),
        ),
    ]
