# Generated by Django 5.0.2 on 2024-02-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_image_url_alter_movie_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='product_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
