# Generated by Django 4.2.6 on 2024-06-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_metascore'),
        ('movies', '0006_alter_movie_image_url_alter_movie_product_url'),
    ]

    operations = [
    ]
