# Generated by Django 4.2.6 on 2024-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_merge_20240623_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='product_url',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.URLField(),
        ),
    ]
